const translations = {
  uk: {
    page_title: "Мій сайт",
    language_label: "Мова:",
    header_title: "Створення сучасних сайтів та веб-рішень",
    contact_info: "Телефон: +380982243655 | Telegram: @VG12244",
    about_me_title: "Про мене",
    about_me_text:
      "Ласкаво прошу на мій особистий сайт. Мене звати Валерій Гордієць Олексійович. Я навчаюся на 3-му курсі за спеціальністю АКІТР у ХНУ. Займаюся розробкою програмного забезпечення та вебсайтів, використовуючи HTML, CSS та JavaScript.",
    why_choose_me_title: "Чому вам варто вибрати мене",
    price_advantage: "Низька ціна, лендинг від 4000 грн",
    tech_advantage: "Використання сучасних технологій: HTML, CSS, JavaScript",
    speed_advantage:
      "Висока швидкість, сайт буде створено менше ніж за тиждень",
    cooperation_advantage: "Активна співпраця з замовником",
    portfolio_advantage:
      "Особлива можливість поповнити портфоліо молодого фронтендера",
    projects_title: "Мої проекти",
    project1_link: "посилання на проект webstudio",
    project2_link: "посилання на проект магазину продуктів",
    calculator_title: "Калькулятор вартості сайту",
    site_type_label: "Тип сайту:",
    site_type_landing: "Лендинг (4000 грн)",
    site_type_business_card: "Візитка (6500 грн)",
    languages_label: "Кількість мов:",
    languages_1: "1 (0 грн)",
    languages_2: "2 (800 грн)",
    languages_3: "3 (1500 грн)",
    animations_label: "Анімації:",
    animations_none: "Немає (0 грн)",
    animations_basic: "Базові (800 грн)",
    animations_complex: "Складні (2000 грн)",
    design_label: "Дизайн:",
    design_template: "Готовий шаблон (0 грн)",
    design_individual: "Індивідуальний (1000 грн)",
    seo_label: "Розширена SEO оптимізація:",
    seo_no: "Ні (0 грн)",
    seo_yes: "Так (900 грн)",
    urgency_label: "Терміновість:",
    urgency_standard: "Стандартний термін",
    urgency_urgent: "Терміново (націнка 30%)",
    calculate_button: "Розрахувати",
    feedback_title: "Залишити відгук",
    name_label: "Ваше ім'я:",
    rating_label: "Ваша оцінка:",
    review_label: "Ваш відгук:",
    send_button: "Відправити",
    recent_feedbacks_title: "Останні відгуки",
    copyright_text: "© 2025 Мій сайт",
    contact_info_footer: "Телефон: +380982243655 | Telegram: @VG12244",
    alert_rating: "Будь ласка, поставте оцінку!",
    no_feedbacks: "Поки що немає відгуків.",
    currency: " грн",
  },
  ru: {
    page_title: "Мой сайт",
    language_label: "Язык:",
    header_title: "Создание современных сайтов и веб-решений",
    contact_info: "Телефон: +380982243655 | Telegram: @VG12244",
    about_me_title: "Обо мне",
    about_me_text:
      "Добро пожаловать на мой личный сайт. Меня зовут Валерий Гордиец Алексеевич. Я учусь на 3-м курсе по специальности АКИТР в ХНУ. Занимаюсь разработкой программного обеспечения и веб-сайтов, используя HTML, CSS и JavaScript.",
    why_choose_me_title: "Почему вам стоит выбрать меня",
    price_advantage: "Низкая цена, лендинг от 4000 грн",
    tech_advantage:
      "Использование современных технологий: HTML, CSS, JavaScript",
    speed_advantage: "Высокая скорость, сайт будет создан менее чем за неделю",
    cooperation_advantage: "Активное сотрудничество с заказчиком",
    portfolio_advantage:
      "Особая возможность пополнить портфолио молодого фронтендера",
    projects_title: "Мои проекты",
    project1_link: "ссылка на проект webstudio",
    project2_link: "ссылка на проект магазина продуктов",
    calculator_title: "Калькулятор стоимости сайта",
    site_type_label: "Тип сайта:",
    site_type_landing: "Лендинг (4000 грн)",
    site_type_business_card: "Визитка (6500 грн)",
    languages_label: "Количество языков:",
    languages_1: "1 (0 грн)",
    languages_2: "2 (800 грн)",
    languages_3: "3 (1500 грн)",
    animations_label: "Анимации:",
    animations_none: "Нет (0 грн)",
    animations_basic: "Базовые (800 грн)",
    animations_complex: "Сложные (2000 грн)",
    design_label: "Дизайн:",
    design_template: "Готовый шаблон (0 грн)",
    design_individual: "Индивидуальный (1000 грн)",
    seo_label: "Расширенная SEO оптимизация:",
    seo_no: "Нет (0 грн)",
    seo_yes: "Да (900 грн)",
    urgency_label: "Срочность:",
    urgency_standard: "Стандартный срок",
    urgency_urgent: "Срочно (наценка 30%)",
    calculate_button: "Рассчитать",
    feedback_title: "Оставить отзыв",
    name_label: "Ваше имя:",
    rating_label: "Ваша оценка:",
    review_label: "Ваш отзыв:",
    send_button: "Отправить",
    recent_feedbacks_title: "Последние отзывы",
    copyright_text: "© 2025 Мой сайт",
    contact_info_footer: "Телефон: +380982243655 | Telegram: @VG12244",
    alert_rating: "Пожалуйста, поставьте оценку!",
    no_feedbacks: "Пока нет отзывов.",
    currency: " грн",
  },
  en: {
    page_title: "My Website",
    language_label: "Language:",
    header_title: "Creating Modern Websites and Web Solutions",
    contact_info: "Phone: +380982243655 | Telegram: @VG12244",
    about_me_title: "About Me",
    about_me_text:
      "Welcome to my personal website. My name is Valerii Hordiets Oleksiiovych. I am a 3rd-year student specializing in AKITR at KhNU. I develop software and websites using HTML, CSS, and JavaScript.",
    why_choose_me_title: "Why You Should Choose Me",
    price_advantage: "Low price, landing page from $100",
    tech_advantage: "Use of modern technologies: HTML, CSS, JavaScript",
    speed_advantage: "High speed, website will be created in less than a week",
    cooperation_advantage: "Active cooperation with the client",
    portfolio_advantage:
      "A great opportunity to expand a young front-ender's portfolio",
    projects_title: "My Projects",
    project1_link: "link to webstudio project",
    project2_link: "link to grocery store project",
    calculator_title: "Website Cost Calculator",
    site_type_label: "Site Type:",
    site_type_landing: "Landing Page ($100)",
    site_type_business_card: "Business Card ($170)",
    languages_label: "Number of Languages:",
    languages_1: "1 ($0)",
    languages_2: "2 ($20)",
    languages_3: "3 ($40)",
    animations_label: "Animations:",
    animations_none: "None ($0)",
    animations_basic: "Basic ($20)",
    animations_complex: "Complex ($50)",
    design_label: "Design:",
    design_template: "Ready-made template ($0)",
    design_individual: "Individual ($30)",
    seo_label: "Advanced SEO Optimization:",
    seo_no: "No ($0)",
    seo_yes: "Yes ($30)",
    urgency_label: "Urgency:",
    urgency_standard: "Standard term",
    urgency_urgent: "Urgent (30% markup)",
    calculate_button: "Calculate",
    feedback_title: "Leave a Review",
    name_label: "Your Name:",
    rating_label: "Your Rating:",
    review_label: "Your Review:",
    send_button: "Send",
    recent_feedbacks_title: "Recent Reviews",
    copyright_text: "© 2025 My Website",
    contact_info_footer: "Phone: +380982243655 | Telegram: @VG12244",
    alert_rating: "Please provide a rating!",
    no_feedbacks: "No reviews yet.",
    currency: " USD",
  },
};

const languageSelect = document.getElementById("language-select");

function setLanguage(lang) {
  document.querySelectorAll("[data-lang-key]").forEach((element) => {
    const key = element.getAttribute("data-lang-key");
    if (translations[lang][key]) {
      element.innerText = translations[lang][key];
    }
  });
}

languageSelect.addEventListener("change", (event) => {
  setLanguage(event.target.value);
});

// Set default language on page load
document.addEventListener("DOMContentLoaded", () => {
  setLanguage("uk");
});
